/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flammiaramos;


public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        this.setResizable(false);
        initComponents();
        
        this.guionPanel.setName("narrativa");
        this.nivelesPanel.setName("nivel");
        this.spritesPanel.setName("sprites");
        this.logicPanel.setName("sistema");
        this.DLCPanel.setName("DLC");
        this.integPanel.setName("integradores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devsPanel = new javax.swing.JPanel();
        devCA = new javax.swing.JLabel();
        devNI = new javax.swing.JLabel();
        logicPanel = new javax.swing.JPanel();
        logicLbl = new javax.swing.JLabel();
        NILogic = new javax.swing.JSpinner();
        CALogic = new javax.swing.JSpinner();
        DLCPanel = new javax.swing.JPanel();
        DLC = new javax.swing.JLabel();
        NIDLC = new javax.swing.JSpinner();
        CADLC = new javax.swing.JSpinner();
        devsQtyPanel = new javax.swing.JPanel();
        devQtyCA = new javax.swing.JLabel();
        devQty = new javax.swing.JLabel();
        devQtyNI = new javax.swing.JLabel();
        integPanel = new javax.swing.JPanel();
        integs = new javax.swing.JLabel();
        integsNI = new javax.swing.JSpinner();
        integsCA = new javax.swing.JSpinner();
        spritesPanel = new javax.swing.JPanel();
        sprites = new javax.swing.JLabel();
        spritesNI = new javax.swing.JSpinner();
        spritesCA = new javax.swing.JSpinner();
        guionPanel = new javax.swing.JPanel();
        guiones = new javax.swing.JLabel();
        guionesNI = new javax.swing.JSpinner();
        guionesCA = new javax.swing.JSpinner();
        nivelesPanel = new javax.swing.JPanel();
        niveles = new javax.swing.JLabel();
        nivelesNI = new javax.swing.JSpinner();
        nivelesCA = new javax.swing.JSpinner();
        tituloDevs = new javax.swing.JLabel();
        disponibilidadPanel = new javax.swing.JPanel();
        tituloDispon = new javax.swing.JLabel();
        disponCA = new javax.swing.JLabel();
        disponNI = new javax.swing.JLabel();
        DLCPanDispon = new javax.swing.JPanel();
        DLCDispon = new javax.swing.JLabel();
        DLCDisponNI = new javax.swing.JLabel();
        DLCDisponCA = new javax.swing.JLabel();
        nivelesPanelDispon = new javax.swing.JPanel();
        nivelesDispon = new javax.swing.JLabel();
        nivelesDisponNI = new javax.swing.JLabel();
        nivelesDisponCA = new javax.swing.JLabel();
        logicPanelDispon = new javax.swing.JPanel();
        sistemasDispon = new javax.swing.JLabel();
        logicDisponNI = new javax.swing.JLabel();
        logicDisponCA = new javax.swing.JLabel();
        narrativaPanelDispon = new javax.swing.JPanel();
        guionesDispon = new javax.swing.JLabel();
        guionesDisponNI = new javax.swing.JLabel();
        guionesDisponCA = new javax.swing.JLabel();
        spritesPanelDispon = new javax.swing.JPanel();
        spritesDispon = new javax.swing.JLabel();
        spritesDisponNI = new javax.swing.JLabel();
        spritesDisponCA = new javax.swing.JLabel();
        maxCapacidad = new javax.swing.JPanel();
        capMax = new javax.swing.JLabel();
        guionesMax = new javax.swing.JLabel();
        nivelesMax = new javax.swing.JLabel();
        spritesMax = new javax.swing.JLabel();
        sistemasMax = new javax.swing.JLabel();
        DLCMax = new javax.swing.JLabel();
        spritesMaxN = new javax.swing.JLabel();
        guionesMaxN = new javax.swing.JLabel();
        nivelesMaxN = new javax.swing.JLabel();
        DLCMaxN = new javax.swing.JLabel();
        sitemasMaxN = new javax.swing.JLabel();
        listos = new javax.swing.JPanel();
        listosTitle = new javax.swing.JLabel();
        listosTitleCA = new javax.swing.JLabel();
        listosTitleNI = new javax.swing.JLabel();
        conDLC = new javax.swing.JLabel();
        qtyListosDLCNI = new javax.swing.JLabel();
        qtyListosDLCCA = new javax.swing.JLabel();
        Est = new javax.swing.JLabel();
        qtyListosEstNI = new javax.swing.JLabel();
        qtyListosEstCA = new javax.swing.JLabel();
        deadlinePanel = new javax.swing.JPanel();
        deadline = new javax.swing.JLabel();
        deadlineN = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devsPanel.setOpaque(false);
        devsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devCA.setForeground(new java.awt.Color(255, 255, 255));
        devCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devCA.setText("CA");
        devsPanel.add(devCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 30, 20));

        devNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        devNI.setForeground(new java.awt.Color(255, 255, 255));
        devNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devNI.setText("NI");
        devsPanel.add(devNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 20));

        logicPanel.setOpaque(false);
        logicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logicLbl.setForeground(new java.awt.Color(255, 255, 255));
        logicLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logicLbl.setText("Sistemas");
        logicPanel.add(logicLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        NILogic.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        NILogic.setModel(new javax.swing.SpinnerNumberModel(2, 1, 9, 1));
        NILogic.setToolTipText("");
        NILogic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NILogicStateChanged(evt);
            }
        });
        logicPanel.add(NILogic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        CALogic.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CALogic.setModel(new javax.swing.SpinnerNumberModel(3, 1, 12, 1));
        CALogic.setToolTipText("");
        CALogic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CALogicStateChanged(evt);
            }
        });
        logicPanel.add(CALogic, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        devsPanel.add(logicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        DLCPanel.setOpaque(false);
        DLCPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DLC.setForeground(new java.awt.Color(255, 255, 255));
        DLC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLC.setText("DLC");
        DLCPanel.add(DLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        NIDLC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        NIDLC.setModel(new javax.swing.SpinnerNumberModel(2, 1, 9, 1));
        NIDLC.setToolTipText("");
        NIDLC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NIDLCStateChanged(evt);
            }
        });
        DLCPanel.add(NIDLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        CADLC.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CADLC.setModel(new javax.swing.SpinnerNumberModel(3, 1, 12, 1));
        CADLC.setToolTipText("");
        CADLC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CADLCStateChanged(evt);
            }
        });
        DLCPanel.add(CADLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        devsPanel.add(DLCPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        devsQtyPanel.setOpaque(false);
        devsQtyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        devQtyCA.setForeground(new java.awt.Color(255, 255, 255));
        devQtyCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devQtyCA.setText("0");
        devsQtyPanel.add(devQtyCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 20));

        devQty.setForeground(new java.awt.Color(255, 255, 255));
        devQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devQty.setText("Devs");
        devsQtyPanel.add(devQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 20));

        devQtyNI.setForeground(new java.awt.Color(255, 255, 255));
        devQtyNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devQtyNI.setText("0");
        devsQtyPanel.add(devQtyNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        devsPanel.add(devsQtyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        integPanel.setOpaque(false);
        integPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        integs.setForeground(new java.awt.Color(255, 255, 255));
        integs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        integs.setText("Integradores");
        integPanel.add(integs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        integsNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        integsNI.setModel(new javax.swing.SpinnerNumberModel(2, 1, 9, 1));
        integsNI.setToolTipText("");
        integsNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                integsNIStateChanged(evt);
            }
        });
        integPanel.add(integsNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        integsCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        integsCA.setModel(new javax.swing.SpinnerNumberModel(2, 1, 12, 1));
        integsCA.setToolTipText("");
        integsCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                integsCAStateChanged(evt);
            }
        });
        integPanel.add(integsCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        devsPanel.add(integPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        spritesPanel.setOpaque(false);
        spritesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sprites.setForeground(new java.awt.Color(255, 255, 255));
        sprites.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sprites.setText("Sprites");
        spritesPanel.add(sprites, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        spritesNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        spritesNI.setModel(new javax.swing.SpinnerNumberModel(2, 1, 9, 1));
        spritesNI.setToolTipText("");
        spritesNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spritesNIStateChanged(evt);
            }
        });
        spritesPanel.add(spritesNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        spritesCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        spritesCA.setModel(new javax.swing.SpinnerNumberModel(3, 1, 12, 1));
        spritesCA.setToolTipText("");
        spritesCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spritesCAStateChanged(evt);
            }
        });
        spritesPanel.add(spritesCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        devsPanel.add(spritesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        guionPanel.setOpaque(false);
        guionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guiones.setForeground(new java.awt.Color(255, 255, 255));
        guiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guiones.setText("Guiones");
        guionPanel.add(guiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        guionesNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guionesNI.setModel(new javax.swing.SpinnerNumberModel(3, 1, 9, 1));
        guionesNI.setToolTipText("");
        guionesNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guionesNIStateChanged(evt);
            }
        });
        guionPanel.add(guionesNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        guionesCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guionesCA.setModel(new javax.swing.SpinnerNumberModel(3, 1, 12, 1));
        guionesCA.setToolTipText("");
        guionesCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guionesCAStateChanged(evt);
            }
        });
        guionPanel.add(guionesCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        devsPanel.add(guionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        nivelesPanel.setOpaque(false);
        nivelesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        niveles.setForeground(new java.awt.Color(255, 255, 255));
        niveles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        niveles.setText("Niveles");
        nivelesPanel.add(niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 20));

        nivelesNI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nivelesNI.setModel(new javax.swing.SpinnerNumberModel(3, 1, 9, 1));
        nivelesNI.setToolTipText("");
        nivelesNI.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nivelesNIStateChanged(evt);
            }
        });
        nivelesPanel.add(nivelesNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, -1));

        nivelesCA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        nivelesCA.setModel(new javax.swing.SpinnerNumberModel(3, 1, 12, 1));
        nivelesCA.setToolTipText("");
        nivelesCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nivelesCAStateChanged(evt);
            }
        });
        nivelesPanel.add(nivelesCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        devsPanel.add(nivelesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        tituloDevs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloDevs.setForeground(new java.awt.Color(255, 255, 255));
        tituloDevs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDevs.setText("DEVELOPERS");
        devsPanel.add(tituloDevs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 20));

        getContentPane().add(devsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 210, 250));

        disponibilidadPanel.setOpaque(false);
        disponibilidadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloDispon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tituloDispon.setForeground(new java.awt.Color(255, 255, 255));
        tituloDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDispon.setText("Disponibilidad");
        disponibilidadPanel.add(tituloDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 20));

        disponCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disponCA.setForeground(new java.awt.Color(255, 255, 255));
        disponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disponCA.setText("CA");
        disponibilidadPanel.add(disponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 30, 20));

        disponNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disponNI.setForeground(new java.awt.Color(255, 255, 255));
        disponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disponNI.setText("NI");
        disponibilidadPanel.add(disponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 20));

        DLCPanDispon.setOpaque(false);
        DLCPanDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DLCDispon.setForeground(new java.awt.Color(255, 255, 255));
        DLCDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCDispon.setText("DLC");
        DLCPanDispon.add(DLCDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        DLCDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        DLCDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCDisponNI.setText("0");
        DLCPanDispon.add(DLCDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        DLCDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        DLCDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCDisponCA.setText("0");
        DLCPanDispon.add(DLCDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(DLCPanDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        nivelesPanelDispon.setOpaque(false);
        nivelesPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nivelesDispon.setForeground(new java.awt.Color(255, 255, 255));
        nivelesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesDispon.setText("Niveles");
        nivelesPanelDispon.add(nivelesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        nivelesDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        nivelesDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesDisponNI.setText("0");
        nivelesPanelDispon.add(nivelesDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        nivelesDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        nivelesDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesDisponCA.setText("0");
        nivelesPanelDispon.add(nivelesDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(nivelesPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        logicPanelDispon.setOpaque(false);
        logicPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sistemasDispon.setForeground(new java.awt.Color(255, 255, 255));
        sistemasDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sistemasDispon.setText("Sistemas");
        logicPanelDispon.add(sistemasDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        logicDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        logicDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logicDisponNI.setText("0");
        logicPanelDispon.add(logicDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        logicDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        logicDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logicDisponCA.setText("0");
        logicPanelDispon.add(logicDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(logicPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        narrativaPanelDispon.setOpaque(false);
        narrativaPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guionesDispon.setForeground(new java.awt.Color(255, 255, 255));
        guionesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDispon.setText("Guiones");
        narrativaPanelDispon.add(guionesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        guionesDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        guionesDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDisponNI.setText("0");
        narrativaPanelDispon.add(guionesDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        guionesDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        guionesDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesDisponCA.setText("0");
        narrativaPanelDispon.add(guionesDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(narrativaPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        spritesPanelDispon.setOpaque(false);
        spritesPanelDispon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spritesDispon.setForeground(new java.awt.Color(255, 255, 255));
        spritesDispon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesDispon.setText("Sprite Sets");
        spritesPanelDispon.add(spritesDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        spritesDisponNI.setForeground(new java.awt.Color(255, 255, 255));
        spritesDisponNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesDisponNI.setText("0");
        spritesPanelDispon.add(spritesDisponNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 20));

        spritesDisponCA.setForeground(new java.awt.Color(255, 255, 255));
        spritesDisponCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesDisponCA.setText("0");
        spritesPanelDispon.add(spritesDisponCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 30, 20));

        disponibilidadPanel.add(spritesPanelDispon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        getContentPane().add(disponibilidadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 160, 220));

        maxCapacidad.setOpaque(false);
        maxCapacidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capMax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        capMax.setForeground(new java.awt.Color(255, 255, 255));
        capMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capMax.setText("Capacidad Máxima");
        maxCapacidad.add(capMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        guionesMax.setForeground(new java.awt.Color(255, 255, 255));
        guionesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guionesMax.setText("Guiones");
        maxCapacidad.add(guionesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        nivelesMax.setForeground(new java.awt.Color(255, 255, 255));
        nivelesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nivelesMax.setText("Niveles");
        maxCapacidad.add(nivelesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 20));

        spritesMax.setForeground(new java.awt.Color(255, 255, 255));
        spritesMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        spritesMax.setText("Sets de Sprites");
        maxCapacidad.add(spritesMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 20));

        sistemasMax.setForeground(new java.awt.Color(255, 255, 255));
        sistemasMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sistemasMax.setText("Sistemas");
        maxCapacidad.add(sistemasMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 20));

        DLCMax.setForeground(new java.awt.Color(255, 255, 255));
        DLCMax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DLCMax.setText("DLCs");
        maxCapacidad.add(DLCMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 100, 20));

        spritesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        spritesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spritesMaxN.setText("0");
        maxCapacidad.add(spritesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, 20));

        guionesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        guionesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guionesMaxN.setText("0");
        maxCapacidad.add(guionesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 30, 20));

        nivelesMaxN.setForeground(new java.awt.Color(255, 255, 255));
        nivelesMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nivelesMaxN.setText("0");
        maxCapacidad.add(nivelesMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 30, 20));

        DLCMaxN.setForeground(new java.awt.Color(255, 255, 255));
        DLCMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DLCMaxN.setText("0");
        maxCapacidad.add(DLCMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, 20));

        sitemasMaxN.setForeground(new java.awt.Color(255, 255, 255));
        sitemasMaxN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sitemasMaxN.setText("0");
        maxCapacidad.add(sitemasMaxN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 30, 20));

        getContentPane().add(maxCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 130, 130));

        listos.setOpaque(false);
        listos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listosTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitle.setForeground(new java.awt.Color(255, 255, 255));
        listosTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitle.setText("Videojuegos Listos");
        listos.add(listosTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 20));

        listosTitleCA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitleCA.setForeground(new java.awt.Color(255, 255, 255));
        listosTitleCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitleCA.setText("CA");
        listos.add(listosTitleCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 30, 20));

        listosTitleNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listosTitleNI.setForeground(new java.awt.Color(255, 255, 255));
        listosTitleNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listosTitleNI.setText("NI");
        listos.add(listosTitleNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 30, 20));

        conDLC.setForeground(new java.awt.Color(255, 255, 255));
        conDLC.setText("Con DLC");
        listos.add(conDLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        qtyListosDLCNI.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosDLCNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosDLCNI.setText("0");
        listos.add(qtyListosDLCNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 30, -1));

        qtyListosDLCCA.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosDLCCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosDLCCA.setText("0");
        listos.add(qtyListosDLCCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 30, -1));

        Est.setForeground(new java.awt.Color(255, 255, 255));
        Est.setText("Estándar");
        listos.add(Est, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        qtyListosEstNI.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosEstNI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosEstNI.setText("0");
        listos.add(qtyListosEstNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 30, -1));

        qtyListosEstCA.setForeground(new java.awt.Color(255, 255, 255));
        qtyListosEstCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyListosEstCA.setText("0");
        listos.add(qtyListosEstCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 30, -1));

        getContentPane().add(listos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        deadlinePanel.setOpaque(false);
        deadlinePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deadline.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deadline.setForeground(new java.awt.Color(255, 255, 255));
        deadline.setText("Deadline");
        deadlinePanel.add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        deadlineN.setForeground(new java.awt.Color(255, 255, 255));
        deadlineN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deadlineN.setText("30");
        deadlinePanel.add(deadlineN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, -1));

        getContentPane().add(deadlinePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 140, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NILogicStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NILogicStateChanged

    }//GEN-LAST:event_NILogicStateChanged

    private void CALogicStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CALogicStateChanged

    }//GEN-LAST:event_CALogicStateChanged

    private void NIDLCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NIDLCStateChanged
        
    }//GEN-LAST:event_NIDLCStateChanged

    private void CADLCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CADLCStateChanged
        
    }//GEN-LAST:event_CADLCStateChanged

    private void integsNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_integsNIStateChanged
        
    }//GEN-LAST:event_integsNIStateChanged

    private void integsCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_integsCAStateChanged
        
    }//GEN-LAST:event_integsCAStateChanged

    private void spritesNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spritesNIStateChanged
        
    }//GEN-LAST:event_spritesNIStateChanged

    private void spritesCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spritesCAStateChanged
        
    }//GEN-LAST:event_spritesCAStateChanged

    private void guionesNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guionesNIStateChanged
        
    }//GEN-LAST:event_guionesNIStateChanged

    private void guionesCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guionesCAStateChanged
        
    }//GEN-LAST:event_guionesCAStateChanged

    private void nivelesNIStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nivelesNIStateChanged
        
    }//GEN-LAST:event_nivelesNIStateChanged

    private void nivelesCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nivelesCAStateChanged
        
    }//GEN-LAST:event_nivelesCAStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CADLC;
    private javax.swing.JSpinner CALogic;
    private javax.swing.JLabel DLC;
    private javax.swing.JLabel DLCDispon;
    private javax.swing.JLabel DLCDisponCA;
    private javax.swing.JLabel DLCDisponNI;
    private javax.swing.JLabel DLCMax;
    private javax.swing.JLabel DLCMaxN;
    private javax.swing.JPanel DLCPanDispon;
    private javax.swing.JPanel DLCPanel;
    private javax.swing.JLabel Est;
    private javax.swing.JLabel Fondo;
    private javax.swing.JSpinner NIDLC;
    private javax.swing.JSpinner NILogic;
    private javax.swing.JLabel capMax;
    private javax.swing.JLabel conDLC;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel deadlineN;
    private javax.swing.JPanel deadlinePanel;
    private javax.swing.JLabel devCA;
    private javax.swing.JLabel devNI;
    private javax.swing.JLabel devQty;
    private javax.swing.JLabel devQtyCA;
    private javax.swing.JLabel devQtyNI;
    private javax.swing.JPanel devsPanel;
    private javax.swing.JPanel devsQtyPanel;
    private javax.swing.JLabel disponCA;
    private javax.swing.JLabel disponNI;
    private javax.swing.JPanel disponibilidadPanel;
    private javax.swing.JPanel guionPanel;
    private javax.swing.JLabel guiones;
    private javax.swing.JSpinner guionesCA;
    private javax.swing.JLabel guionesDispon;
    private javax.swing.JLabel guionesDisponCA;
    private javax.swing.JLabel guionesDisponNI;
    private javax.swing.JLabel guionesMax;
    private javax.swing.JLabel guionesMaxN;
    private javax.swing.JSpinner guionesNI;
    private javax.swing.JPanel integPanel;
    private javax.swing.JLabel integs;
    private javax.swing.JSpinner integsCA;
    private javax.swing.JSpinner integsNI;
    private javax.swing.JPanel listos;
    private javax.swing.JLabel listosTitle;
    private javax.swing.JLabel listosTitleCA;
    private javax.swing.JLabel listosTitleNI;
    private javax.swing.JLabel logicDisponCA;
    private javax.swing.JLabel logicDisponNI;
    private javax.swing.JLabel logicLbl;
    private javax.swing.JPanel logicPanel;
    private javax.swing.JPanel logicPanelDispon;
    private javax.swing.JPanel maxCapacidad;
    private javax.swing.JPanel narrativaPanelDispon;
    private javax.swing.JLabel niveles;
    private javax.swing.JSpinner nivelesCA;
    private javax.swing.JLabel nivelesDispon;
    private javax.swing.JLabel nivelesDisponCA;
    private javax.swing.JLabel nivelesDisponNI;
    private javax.swing.JLabel nivelesMax;
    private javax.swing.JLabel nivelesMaxN;
    private javax.swing.JSpinner nivelesNI;
    private javax.swing.JPanel nivelesPanel;
    private javax.swing.JPanel nivelesPanelDispon;
    private javax.swing.JLabel qtyListosDLCCA;
    private javax.swing.JLabel qtyListosDLCNI;
    private javax.swing.JLabel qtyListosEstCA;
    private javax.swing.JLabel qtyListosEstNI;
    private javax.swing.JLabel sistemasDispon;
    private javax.swing.JLabel sistemasMax;
    private javax.swing.JLabel sitemasMaxN;
    private javax.swing.JLabel sprites;
    private javax.swing.JSpinner spritesCA;
    private javax.swing.JLabel spritesDispon;
    private javax.swing.JLabel spritesDisponCA;
    private javax.swing.JLabel spritesDisponNI;
    private javax.swing.JLabel spritesMax;
    private javax.swing.JLabel spritesMaxN;
    private javax.swing.JSpinner spritesNI;
    private javax.swing.JPanel spritesPanel;
    private javax.swing.JPanel spritesPanelDispon;
    private javax.swing.JLabel tituloDevs;
    private javax.swing.JLabel tituloDispon;
    // End of variables declaration//GEN-END:variables
}
